#include <defs.h>
//#include <math.h>
#include <stub.h>
#include <hw/common.h>
#include <uart.h>
#include <uart_api.h>

// --------------------------------------------------------
// Firmware routines
// --------------------------------------------------------

void configure_io()
{

    //  GPIO 0 is turned off to prevent toggling the debug pin; For debug, make this an output and
    //  drive it externally to ground.

    reg_mprj_io_0 = GPIO_MODE_MGMT_STD_ANALOG;

    // Changing configuration for IO[1-4] will interfere with programming flash. if you change them,
    // You may need to hold reset while powering up the board and initiating flash to keep the process
    // configuring these IO from their default values.

    reg_mprj_io_1 = GPIO_MODE_MGMT_STD_OUTPUT;
    reg_mprj_io_2 = GPIO_MODE_MGMT_STD_INPUT_NOPULL;
    reg_mprj_io_3 = GPIO_MODE_MGMT_STD_INPUT_NOPULL;
    reg_mprj_io_4 = GPIO_MODE_MGMT_STD_INPUT_NOPULL;

    // pins for the 7 seg counter
    reg_mprj_io_29 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_30 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_31 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_32 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_33 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_34 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_35 = GPIO_MODE_MGMT_STD_OUTPUT; 
    reg_mprj_io_36 = GPIO_MODE_MGMT_STD_OUTPUT; 

    // Initiate the serial transfer to configure IO
    reg_mprj_xfer = 1;
    while (reg_mprj_xfer == 1);
}

void delay(const int d)
{

    /* Configure timer for a single-shot countdown */
	reg_timer0_config = 0;
	reg_timer0_data = d;
    reg_timer0_config = 1;

    // Loop, waiting for value to reach zero
   reg_timer0_update = 1;  // latch current value
   while (reg_timer0_value > 0) {
           reg_timer0_update = 1;
   }

}

#define DELAY 5000000
void main()
{
	int i, j, k;

    reg_gpio_mode1 = 1;
    reg_gpio_mode0 = 0;
    reg_gpio_ien = 1;
    reg_gpio_oe = 1;

    configure_io();

	while (1) {
        // these values generated by gen_hex_count.py

        reg_mprj_datah = 0x7; reg_mprj_datal = 0xe0000000; delay(DELAY);
        reg_mprj_datah = 0x0; reg_mprj_datal = 0xc0000000; delay(DELAY);
        reg_mprj_datah = 0xb; reg_mprj_datal = 0x60000000; delay(DELAY);
        reg_mprj_datah = 0x9; reg_mprj_datal = 0xe0000000; delay(DELAY);
        reg_mprj_datah = 0xc; reg_mprj_datal = 0xc0000000; delay(DELAY);
        reg_mprj_datah = 0xd; reg_mprj_datal = 0xa0000000; delay(DELAY);
        reg_mprj_datah = 0xf; reg_mprj_datal = 0x80000000; delay(DELAY);
        reg_mprj_datah = 0x0; reg_mprj_datal = 0xe0000000; delay(DELAY);
        reg_mprj_datah = 0xf; reg_mprj_datal = 0xe0000000; delay(DELAY);
        reg_mprj_datah = 0xc; reg_mprj_datal = 0xe0000000; delay(DELAY);
    }
}
